---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas

  tasks:
    - name: Install SQL Server Express 2022 using Chocolatey
      win_chocolatey:
        name: sql-server-express
        version: '2022'
        state: present
        params:
          InstallDir: 'C:\Program Files\Microsoft SQL Server'
          InstanceName: 'SQLEXPRESS'
          Features: 'SQLENGINE,Replication,FullText'
          SQLSVCACCOUNT: 'NT AUTHORITY\NETWORK SERVICE'
          AGTSVCACCOUNT: 'NT AUTHORITY\NETWORK SERVICE'
          SQLSYSADMINACCOUNTS: 'BUILTIN\Administrators'
          SECURITYMODE: 'SQL'
          SAPWD: 'YourStrongPassword'

    - name: Start SQL Server service
      win_service:
        name: MSSQL$SQLEXPRESS
        start_mode: auto
        state: started