---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
    - name: Debug message for MySQL installation status
      debug:
        msg: "MSSQLEXPRESS installation on process.."

    - name: Install SQL Server Express 2022 using Chocolatey
      win_chocolatey:
        name: sql-server-express
        #version: '2022.16.0.1000'
        #source: https://community.chocolatey.org/api/v2/
        state: present
        #params:
          #InstallDir: 'C:\Program Files\Microsoft SQL Server'
          #acceptlicense: yes
          #InstanceName: 'SQLEXPRESS'
          #Features: 'SQLENGINE,Replication,FullText'
          #SQLSVCACCOUNT: 'NT AUTHORITY\NETWORK SERVICE'
          #AGTSVCACCOUNT: 'NT AUTHORITY\NETWORK SERVICE'
          #SQLSYSADMINACCOUNTS: 'BUILTIN\Administrators'
          #SECURITYMODE: 'SQL'
          #SAPWD: '{{ sa_password }}'
        
    

    #- name: Start SQL Server service
      #win_service:
        #name: MSSQL$SQLEXPRESS
        #start_mode: auto
        #state: started

    - name: Debug message for MySQL service status
      debug:
        msg: "MSSQLEXPRESS service installation successfully."