---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas

  tasks:
    - name: Install SQL Server Express 2022 using Chocolatey
      win_chocolatey:
        name: sql-server-express
        #version: '2022.16.0.1000'
        #source: http://internal/odata/repo
        state: present
        params:
          InstallDir: 'C:\Program Files\Microsoft SQL Server'
          InstanceName: 'SQLEXPRESS'
          Features: 'SQLENGINE,Replication,FullText'
          SQLSVCACCOUNT: 'NT AUTHORITY\NETWORK SERVICE'
          AGTSVCACCOUNT: 'NT AUTHORITY\NETWORK SERVICE'
          SQLSYSADMINACCOUNTS: 'BUILTIN\Administrators'
          SECURITYMODE: 'SQL'
          SAPWD: '{{ sa_password }}'
        
    - name: Debug message for MySQL installation status
      debug:
        msg: "MSSQLEXPRESS installation on process.."

    - name: Start SQL Server service
      win_service:
        name: MSSQL$SQLEXPRESS
        start_mode: auto
        state: started

    - name: Debug message for MySQL service status
      debug:
        msg: "MSSQLEXPRESS service installation successfully."