---
- hosts: localhost
  gather_facts: no
  #vars:
    #vcenter: "172.18.0.60"
    #username: "administrator@vsphere.local"
    #password: "xP@ssw0rd@123"
  tasks:

    - name: Create VM from template
      community.vmware.vmware_guest:
        hostname: "m79.cloud.ksc.net"
        username: "yuttanah"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "MTG"
        folder: "MTG/vm/"
        datastore: "vSanDatastore"
        name: "{{ guest_name }}"
        template: "{{ template_name }}"
        state: present
        hardware:
          memory_mb: "4096"
          num_cpus: "4"
          num_cpu_cores_per_socket: "4"
          scsi: paravirtual
        wait_for_ip_address: true
      delegate_to: localhost